version: '3'
services:
  app:
    build: .
    image: cuantificacion
    ports:
      - "8085:80"
    networks:
      - reporte_gei
    volumes:
      - .:/var/www/app
    depends_on:
      - pgdb
  pgdb:
    image: postgres
    networks:
      - reporte_gei
    environment:
      POSTGRES_USER: reporte_gei
      POSTGRES_PASSWORD: osvaldo1249
      POSTGRES_DB: cuantificacion_development
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
  cuantificacion:
    driver: "local"
networks:
  reporte_gei:
